export const APP_VERSION = "v 1.4.2";

export const VERSION_HISTORY = [
  {
    version: APP_VERSION,
    date: "2026-06-08",
    notes: [
      "Botones de acciones del menu simplificados",
      "Eliminacion de productos con confirmacion",
      "Boton Nuevo producto reubicado en la columna lateral",
      "Precio de menu con entrada flexible y guardado numerico",
      "Menu funcional con productos editables",
      "Productos activos e inactivos sincronizados con consumos",
      "Catalogo compartido entre menu y consumos por mesa",
      "Boton de agregar bloque horario con icono unico",
      "Dropdowns nativos con icono interno y padding corregido",
      "Correccion manual de estado disponible desde editar reserva",
      "Sincronizacion automatica de mesa al corregir reservas",
      "Flujo de reserva separado del estado manual de mesa",
      "Acciones rapidas adaptadas segun reserva asociada",
      "Paneles laterales del plano reordenados",
      "Informacion de mesa con resumen de consumos",
      "Interaccion de mesas separa click simple y doble click",
      "Consumos repetidos agrupados por producto",
      "Consumos por mesa agregados desde plano de mesas",
      "Modal de consumos con items persistidos en la sesion",
      "Estado interno y contador de mesas ocupadas corregidos",
      "Contador de mesas ocupadas agregado al plano",
      "Plano de mesas sin modal automatico al entrar",
      "Reservas sincronizadas con estados de mesas",
      "Plano de mesas conectado al flujo de reservas",
      "Modal de vista con ficha premium y acciones rapidas",
      "Modal de edicion con flujo visible y acciones rapidas",
      "Anchos de columnas optimizados en reservas",
      "Tabla de reservas estabilizada con columnas fijas",
      "Acciones de reservas separadas por flujo y acciones",
      "Acciones rapidas y modal con scroll interno en reservas",
      "Reservas funcionales con estado local",
      "Horarios comerciales con bloques largos permitidos",
      "Base visual del SaaS multi-tenant",
      "Layout premium para restaurante y super admin",
    ],
  },
] as const;
