export const APP_VERSION = "v 2.0.4";

export const VERSION_HISTORY = [
  {
    version: APP_VERSION,
    date: "2026-06-09",
    notes: [
      "Limpieza de tabs internas duplicadas en Configuracion",
      "Reportes alineados al periodo activo sin mezclar Hoy, Semana y Mes",
      "Cards principales de reportes calculadas sobre el rango seleccionado",
      "Cierre de estabilidad de flujos operativos del sprint",
      "Sincronizacion del CRM al completar reservas desde el plano",
      "Validacion de configuracion, reservas, plano, reportes, clientes y menu",
      "Confirmacion obligatoria para cambios de duracion e intervalo operativo",
      "Duracion e intervalo normalizados con limites seguros y pasos de 5 minutos",
      "Configuracion operativa conectada al estado local del restaurante",
      "Horarios comerciales centralizados con validacion de duplicados y solapamientos",
      "Duracion, intervalo, auto-confirmacion y lista de espera afectan reservas",
      "Datos del restaurante actualizan el panel interno y sidebar",
      "Dashboard operativo conectado al estado local de reservas y mesas",
      "Metricas del dia actual calculadas con reservas, consumos y clientes reales",
      "Alertas, cumpleanos y ultimas reservas derivadas del flujo operativo",
      "Card de resumen de cantidad de clientes removida del panel izquierdo",
      "Listado de clientes aprovecha el espacio liberado",
      "Scroll independiente en listado izquierdo de Clientes",
      "Resumen y buscador del CRM permanecen visibles",
      "CRM funcional construido desde reservas y consumos locales",
      "Clientes unificados por email o telefono desde reservas",
      "Ficha de cliente con metricas, historial y consumos agrupados",
      "Alertas de cumpleanos, alergias, preferencias y notas internas",
      "Header de Reservas estabilizado entre Hoy, Semana y Mes",
      "Boton Filtros removido del selector superior de Reservas",
      "Filtros rapidos Hoy, Semana, Mes y Personalizado en Reservas",
      "Selector de fecha duplicado reemplazado por control unico de rango",
      "Conteos de estado recalculados segun el rango activo",
      "Normalizacion global de fechas y bloqueo operativo de reservas futuras",
      "Reportes abre por defecto en Hoy con comparaciones yyyy-mm-dd",
      "Reservas futuras no pueden ocuparse, completarse ni cargar consumos",
      "Plano de mesas representa solo la operacion del dia actual",
      "Auditoria de reportes con normalizacion central de fechas",
      "Ventas hoy, semana, mes y personalizado usan la misma fuente de calculo",
      "Semana comercial calculada de lunes a domingo sobre fecha actual",
      "Consumos editables con controles de cantidad y eliminacion directa",
      "Reportes recalculados desde reservas completadas y consumos actuales",
      "Ventas hoy usa la fecha actual del sistema y formato argentino",
      "Sincronizacion defensiva entre reservas y mesas al cargar el plano",
      "Mesas ocupadas o reservadas sin reserva activa vuelven a Libre",
      "Plano de mesas usa solo reservas activas para cliente y consumo",
      "Reportes funcionales con metricas reales sobre datos mock",
      "Filtros Hoy, Semana, Mes y Personalizado para analisis",
      "Exportacion mock a CSV y PDF desde la pantalla de reportes",
      "Top productos, canales y ocupacion calculados desde estado local",
      "Validacion de disponibilidad y conflictos de reservas",
      "Selector de mesas con disponibilidad visual y razones",
      "Errores claros al intentar guardar mesas ocupadas o reservadas",
      "Alertas suaves en reservas para autoasignacion y conflictos",
      "Asignacion automatica de mesa en reservas nuevas y editadas",
      "Cumpleanos convertido a input de fecha en reservas y CRM",
      "Aviso visual cuando no hay mesa disponible automaticamente",
      "CRM funcional conectado a reservas y consumos",
      "Ficha de cliente con historial y edicion",
      "Clientes auto creados o actualizados desde reservas",
      "Botones de acciones del menu simplificados",
      "Eliminacion de productos con confirmacion",
      "Boton Nuevo producto reubicado en la columna lateral",
      "Precio de menu con entrada flexible y guardado numerico",
      "Menu funcional con productos editables",
      "Productos activos e inactivos sincronizados con consumos",
      "Catalogo compartido entre menu y consumos por mesa",
      "Boton de agregar bloque horario con icono unico",
      "Dropdowns nativos con icono interno y padding corregido",
      "Correccion manual de estado disponible desde editar reserva",
      "Sincronizacion automatica de mesa al corregir reservas",
      "Flujo de reserva separado del estado manual de mesa",
      "Acciones rapidas adaptadas segun reserva asociada",
      "Paneles laterales del plano reordenados",
      "Informacion de mesa con resumen de consumos",
      "Interaccion de mesas separa click simple y doble click",
      "Consumos repetidos agrupados por producto",
      "Consumos por mesa agregados desde plano de mesas",
      "Modal de consumos con items persistidos en la sesion",
      "Estado interno y contador de mesas ocupadas corregidos",
      "Contador de mesas ocupadas agregado al plano",
      "Plano de mesas sin modal automatico al entrar",
      "Reservas sincronizadas con estados de mesas",
      "Plano de mesas conectado al flujo de reservas",
      "Modal de vista con ficha premium y acciones rapidas",
      "Modal de edicion con flujo visible y acciones rapidas",
      "Anchos de columnas optimizados en reservas",
      "Tabla de reservas estabilizada con columnas fijas",
      "Acciones de reservas separadas por flujo y acciones",
      "Acciones rapidas y modal con scroll interno en reservas",
      "Reservas funcionales con estado local",
      "Horarios comerciales con bloques largos permitidos",
      "Base visual del SaaS multi-tenant",
      "Layout premium para restaurante y super admin",
    ],
  },
] as const;
